version: "3.3"
services:
  mysqlservice:
    image: mysql:5.7
    ports:
      - "3306:3306"
    container_name: mysql-container
    networks:
      - user-movie-net
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USERNAME: user
      MYSQL_PASSWORD: root
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
  mongodbservice:
    image: mongo:latest
    container_name: mongo-container
    networks:
      - user-movie-net
    ports:
      - "27017:27017"

  userauthenticationservice:
    container_name: user-authentication-service
    build: UserAuthenticationService/
    networks:
      - user-movie-net
    ports:
      - "8085:8085"
    depends_on:
      - mysqlservice
    restart: always

  usermovieservice:
    container_name: user-movie-service
    build: UserMovieService/
    networks:
      - user-movie-net
    ports:
      - "8081:8081"
    depends_on:
      - mongodbservice
    restart: always

networks:
  user-movie-net:
    driver: bridge








